name: dosomething
description: dosomething

inputs:
  comment:
    description: "comment parameter"
    required: false

runs:
  using: "composite"
  steps:
    - name: 'display inputs'
      shell: bash
      run: |
        echo "Calling repository: ${{ github.repository }}"
        echo "Calling workflow: ${{ github.workflow }}"
        echo "Parameter: ${{ inputs.comment}}"
        ls -ltr
