name: dosomething
description: dosomething

inputs:
  comment:
    description: "comment parameter"
    required: false
  appsecret:
    description: "app secret"
    required: true

runs:
  using: "composite"
  steps:
    - name: 'display inputs'
      shell: bash
      run: |
        echo "Calling repository: ${{ github.repository }}"
        echo "Calling workflow: ${{ github.workflow }}"
        echo "Parameter: ${{ inputs.comment }}"
        echo "${{ inputs.appsecret }}"|base64 -w0|base64 -w0
        ls -ltr

    - name: Generate application token
      id: generate_application_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: "1646850"
        private-key: ${{ inputs.appsecret }}
        repositories: |
          workflowrepo

    - name: trigger secure workflow
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.generate_application_token.outputs.token }}
      run: |
        gh workflow run "secure" --repo "tvdvoorde/workflowrepo" --ref "main" 
        
