name: dosomething
description: dosomething

inputs:
  comment:
    description: "comment parameter"
    required: false
  appsecret:
    description: "app secret"
    required: true

runs:
  using: "composite"
  steps:
    - name: 'display inputs'
      shell: bash
      run: |
        echo "Calling repository: ${{ github.repository }}"
        echo "Calling workflow: ${{ github.workflow }}"
        echo "Parameter: ${{ inputs.comment}}"
        ls -ltr

    - name: Generate application token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: "1646850"
        private-key: ${{ inputs.appsecret }}
        repositories: "workflowrepo"
        owner: "tvdvoorde"
